// Generated by scripts/generate-pokemon-evolutions.mjs.
// Source: PokeAPI pokemon-species and evolution-chain resources for National Dex 1-386.
// Do not edit this file by hand; rerun the generator.

export interface PokemonEvolutionDetail {
  trigger?: string;
  minLevel?: number;
  minHappiness?: number;
  minBeauty?: number;
  minAffection?: number;
  item?: string;
  heldItem?: string;
  timeOfDay?: string;
  knownMove?: string;
  knownMoveType?: string;
  location?: string;
  gender?: number;
  needsOverworldRain?: boolean;
  turnUpsideDown?: boolean;
  relativePhysicalStats?: number;
  tradeSpecies?: string;
}

export interface PokemonEvolutionEdge {
  fromId: number;
  from: string;
  toId: number;
  to: string;
  details: PokemonEvolutionDetail[];
}

export const POKEMON_EVOLUTIONS: PokemonEvolutionEdge[] = [
  {
    "fromId": 1,
    "from": "Bulbasaur",
    "toId": 2,
    "to": "Ivysaur",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 2,
    "from": "Ivysaur",
    "toId": 3,
    "to": "Venusaur",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 32
      }
    ]
  },
  {
    "fromId": 4,
    "from": "Charmander",
    "toId": 5,
    "to": "Charmeleon",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 5,
    "from": "Charmeleon",
    "toId": 6,
    "to": "Charizard",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 7,
    "from": "Squirtle",
    "toId": 8,
    "to": "Wartortle",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 8,
    "from": "Wartortle",
    "toId": 9,
    "to": "Blastoise",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 10,
    "from": "Caterpie",
    "toId": 11,
    "to": "Metapod",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 7
      }
    ]
  },
  {
    "fromId": 11,
    "from": "Metapod",
    "toId": 12,
    "to": "Butterfree",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 10
      }
    ]
  },
  {
    "fromId": 13,
    "from": "Weedle",
    "toId": 14,
    "to": "Kakuna",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 7
      }
    ]
  },
  {
    "fromId": 14,
    "from": "Kakuna",
    "toId": 15,
    "to": "Beedrill",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 10
      }
    ]
  },
  {
    "fromId": 16,
    "from": "Pidgey",
    "toId": 17,
    "to": "Pidgeotto",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 18
      }
    ]
  },
  {
    "fromId": 17,
    "from": "Pidgeotto",
    "toId": 18,
    "to": "Pidgeot",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 19,
    "from": "Rattata",
    "toId": 20,
    "to": "Raticate",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      },
      {
        "trigger": "level-up",
        "minLevel": 20,
        "timeOfDay": "night"
      }
    ]
  },
  {
    "fromId": 21,
    "from": "Spearow",
    "toId": 22,
    "to": "Fearow",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 23,
    "from": "Ekans",
    "toId": 24,
    "to": "Arbok",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 22
      }
    ]
  },
  {
    "fromId": 25,
    "from": "Pikachu",
    "toId": 26,
    "to": "Raichu",
    "details": [
      {
        "trigger": "use-item",
        "item": "thunder-stone"
      },
      {
        "trigger": "use-item",
        "item": "thunder-stone"
      }
    ]
  },
  {
    "fromId": 27,
    "from": "Sandshrew",
    "toId": 28,
    "to": "Sandslash",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 22
      },
      {
        "trigger": "use-item",
        "item": "ice-stone"
      }
    ]
  },
  {
    "fromId": 29,
    "from": "Nidoran F",
    "toId": 30,
    "to": "Nidorina",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 30,
    "from": "Nidorina",
    "toId": 31,
    "to": "Nidoqueen",
    "details": [
      {
        "trigger": "use-item",
        "item": "moon-stone"
      }
    ]
  },
  {
    "fromId": 32,
    "from": "Nidoran M",
    "toId": 33,
    "to": "Nidorino",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 33,
    "from": "Nidorino",
    "toId": 34,
    "to": "Nidoking",
    "details": [
      {
        "trigger": "use-item",
        "item": "moon-stone"
      }
    ]
  },
  {
    "fromId": 35,
    "from": "Clefairy",
    "toId": 36,
    "to": "Clefable",
    "details": [
      {
        "trigger": "use-item",
        "item": "moon-stone"
      }
    ]
  },
  {
    "fromId": 37,
    "from": "Vulpix",
    "toId": 38,
    "to": "Ninetales",
    "details": [
      {
        "trigger": "use-item",
        "item": "fire-stone"
      },
      {
        "trigger": "use-item",
        "item": "ice-stone"
      }
    ]
  },
  {
    "fromId": 39,
    "from": "Jigglypuff",
    "toId": 40,
    "to": "Wigglytuff",
    "details": [
      {
        "trigger": "use-item",
        "item": "moon-stone"
      }
    ]
  },
  {
    "fromId": 41,
    "from": "Zubat",
    "toId": 42,
    "to": "Golbat",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 22
      }
    ]
  },
  {
    "fromId": 42,
    "from": "Golbat",
    "toId": 169,
    "to": "Crobat",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 160
      }
    ]
  },
  {
    "fromId": 43,
    "from": "Oddish",
    "toId": 44,
    "to": "Gloom",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 21
      }
    ]
  },
  {
    "fromId": 44,
    "from": "Gloom",
    "toId": 45,
    "to": "Vileplume",
    "details": [
      {
        "trigger": "use-item",
        "item": "leaf-stone"
      }
    ]
  },
  {
    "fromId": 44,
    "from": "Gloom",
    "toId": 182,
    "to": "Bellossom",
    "details": [
      {
        "trigger": "use-item",
        "item": "sun-stone"
      }
    ]
  },
  {
    "fromId": 46,
    "from": "Paras",
    "toId": 47,
    "to": "Parasect",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 24
      }
    ]
  },
  {
    "fromId": 48,
    "from": "Venonat",
    "toId": 49,
    "to": "Venomoth",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 31
      }
    ]
  },
  {
    "fromId": 50,
    "from": "Diglett",
    "toId": 51,
    "to": "Dugtrio",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 26
      },
      {
        "trigger": "level-up",
        "minLevel": 26
      }
    ]
  },
  {
    "fromId": 52,
    "from": "Meowth",
    "toId": 53,
    "to": "Persian",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 28
      },
      {
        "trigger": "level-up",
        "minHappiness": 160
      }
    ]
  },
  {
    "fromId": 54,
    "from": "Psyduck",
    "toId": 55,
    "to": "Golduck",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 33
      }
    ]
  },
  {
    "fromId": 56,
    "from": "Mankey",
    "toId": 57,
    "to": "Primeape",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 28
      }
    ]
  },
  {
    "fromId": 58,
    "from": "Growlithe",
    "toId": 59,
    "to": "Arcanine",
    "details": [
      {
        "trigger": "use-item",
        "item": "fire-stone"
      },
      {
        "trigger": "use-item",
        "item": "fire-stone"
      }
    ]
  },
  {
    "fromId": 60,
    "from": "Poliwag",
    "toId": 61,
    "to": "Poliwhirl",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 25
      }
    ]
  },
  {
    "fromId": 61,
    "from": "Poliwhirl",
    "toId": 62,
    "to": "Poliwrath",
    "details": [
      {
        "trigger": "use-item",
        "item": "water-stone"
      }
    ]
  },
  {
    "fromId": 61,
    "from": "Poliwhirl",
    "toId": 186,
    "to": "Politoed",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "kings-rock"
      }
    ]
  },
  {
    "fromId": 63,
    "from": "Abra",
    "toId": 64,
    "to": "Kadabra",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 64,
    "from": "Kadabra",
    "toId": 65,
    "to": "Alakazam",
    "details": [
      {
        "trigger": "trade"
      }
    ]
  },
  {
    "fromId": 66,
    "from": "Machop",
    "toId": 67,
    "to": "Machoke",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 28
      }
    ]
  },
  {
    "fromId": 67,
    "from": "Machoke",
    "toId": 68,
    "to": "Machamp",
    "details": [
      {
        "trigger": "trade"
      }
    ]
  },
  {
    "fromId": 69,
    "from": "Bellsprout",
    "toId": 70,
    "to": "Weepinbell",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 21
      }
    ]
  },
  {
    "fromId": 70,
    "from": "Weepinbell",
    "toId": 71,
    "to": "Victreebel",
    "details": [
      {
        "trigger": "use-item",
        "item": "leaf-stone"
      }
    ]
  },
  {
    "fromId": 72,
    "from": "Tentacool",
    "toId": 73,
    "to": "Tentacruel",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 74,
    "from": "Geodude",
    "toId": 75,
    "to": "Graveler",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 25
      },
      {
        "trigger": "level-up",
        "minLevel": 25
      }
    ]
  },
  {
    "fromId": 75,
    "from": "Graveler",
    "toId": 76,
    "to": "Golem",
    "details": [
      {
        "trigger": "trade"
      },
      {
        "trigger": "trade"
      }
    ]
  },
  {
    "fromId": 77,
    "from": "Ponyta",
    "toId": 78,
    "to": "Rapidash",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 40
      },
      {
        "trigger": "level-up",
        "minLevel": 40
      }
    ]
  },
  {
    "fromId": 79,
    "from": "Slowpoke",
    "toId": 80,
    "to": "Slowbro",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 37
      },
      {
        "trigger": "use-item",
        "item": "galarica-cuff"
      }
    ]
  },
  {
    "fromId": 79,
    "from": "Slowpoke",
    "toId": 199,
    "to": "Slowking",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "kings-rock"
      },
      {
        "trigger": "use-item",
        "item": "galarica-wreath"
      }
    ]
  },
  {
    "fromId": 81,
    "from": "Magnemite",
    "toId": 82,
    "to": "Magneton",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 84,
    "from": "Doduo",
    "toId": 85,
    "to": "Dodrio",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 31
      }
    ]
  },
  {
    "fromId": 86,
    "from": "Seel",
    "toId": 87,
    "to": "Dewgong",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 34
      }
    ]
  },
  {
    "fromId": 88,
    "from": "Grimer",
    "toId": 89,
    "to": "Muk",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 38
      },
      {
        "trigger": "level-up",
        "minLevel": 38
      }
    ]
  },
  {
    "fromId": 90,
    "from": "Shellder",
    "toId": 91,
    "to": "Cloyster",
    "details": [
      {
        "trigger": "use-item",
        "item": "water-stone"
      }
    ]
  },
  {
    "fromId": 92,
    "from": "Gastly",
    "toId": 93,
    "to": "Haunter",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 25
      }
    ]
  },
  {
    "fromId": 93,
    "from": "Haunter",
    "toId": 94,
    "to": "Gengar",
    "details": [
      {
        "trigger": "trade"
      }
    ]
  },
  {
    "fromId": 95,
    "from": "Onix",
    "toId": 208,
    "to": "Steelix",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "metal-coat"
      }
    ]
  },
  {
    "fromId": 96,
    "from": "Drowzee",
    "toId": 97,
    "to": "Hypno",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 26
      }
    ]
  },
  {
    "fromId": 98,
    "from": "Krabby",
    "toId": 99,
    "to": "Kingler",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 28
      }
    ]
  },
  {
    "fromId": 100,
    "from": "Voltorb",
    "toId": 101,
    "to": "Electrode",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      },
      {
        "trigger": "use-item",
        "item": "leaf-stone"
      }
    ]
  },
  {
    "fromId": 102,
    "from": "Exeggcute",
    "toId": 103,
    "to": "Exeggutor",
    "details": [
      {
        "trigger": "use-item",
        "item": "leaf-stone"
      },
      {
        "trigger": "use-item",
        "item": "leaf-stone"
      }
    ]
  },
  {
    "fromId": 104,
    "from": "Cubone",
    "toId": 105,
    "to": "Marowak",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 28
      },
      {
        "trigger": "level-up",
        "minLevel": 28,
        "timeOfDay": "night"
      }
    ]
  },
  {
    "fromId": 109,
    "from": "Koffing",
    "toId": 110,
    "to": "Weezing",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 35
      },
      {
        "trigger": "level-up",
        "minLevel": 35
      }
    ]
  },
  {
    "fromId": 111,
    "from": "Rhyhorn",
    "toId": 112,
    "to": "Rhydon",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 42
      }
    ]
  },
  {
    "fromId": 116,
    "from": "Horsea",
    "toId": 117,
    "to": "Seadra",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 32
      }
    ]
  },
  {
    "fromId": 117,
    "from": "Seadra",
    "toId": 230,
    "to": "Kingdra",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "dragon-scale"
      }
    ]
  },
  {
    "fromId": 118,
    "from": "Goldeen",
    "toId": 119,
    "to": "Seaking",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 33
      }
    ]
  },
  {
    "fromId": 120,
    "from": "Staryu",
    "toId": 121,
    "to": "Starmie",
    "details": [
      {
        "trigger": "use-item",
        "item": "water-stone"
      }
    ]
  },
  {
    "fromId": 123,
    "from": "Scyther",
    "toId": 212,
    "to": "Scizor",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "metal-coat"
      }
    ]
  },
  {
    "fromId": 129,
    "from": "Magikarp",
    "toId": 130,
    "to": "Gyarados",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 133,
    "from": "Eevee",
    "toId": 134,
    "to": "Vaporeon",
    "details": [
      {
        "trigger": "use-item",
        "item": "water-stone"
      }
    ]
  },
  {
    "fromId": 133,
    "from": "Eevee",
    "toId": 135,
    "to": "Jolteon",
    "details": [
      {
        "trigger": "use-item",
        "item": "thunder-stone"
      }
    ]
  },
  {
    "fromId": 133,
    "from": "Eevee",
    "toId": 136,
    "to": "Flareon",
    "details": [
      {
        "trigger": "use-item",
        "item": "fire-stone"
      }
    ]
  },
  {
    "fromId": 133,
    "from": "Eevee",
    "toId": 196,
    "to": "Espeon",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 160,
        "timeOfDay": "day"
      }
    ]
  },
  {
    "fromId": 133,
    "from": "Eevee",
    "toId": 197,
    "to": "Umbreon",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 160,
        "timeOfDay": "night"
      }
    ]
  },
  {
    "fromId": 137,
    "from": "Porygon",
    "toId": 233,
    "to": "Porygon2",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "up-grade"
      }
    ]
  },
  {
    "fromId": 138,
    "from": "Omanyte",
    "toId": 139,
    "to": "Omastar",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 40
      }
    ]
  },
  {
    "fromId": 140,
    "from": "Kabuto",
    "toId": 141,
    "to": "Kabutops",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 40
      }
    ]
  },
  {
    "fromId": 147,
    "from": "Dratini",
    "toId": 148,
    "to": "Dragonair",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 148,
    "from": "Dragonair",
    "toId": 149,
    "to": "Dragonite",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 55
      }
    ]
  },
  {
    "fromId": 152,
    "from": "Chikorita",
    "toId": 153,
    "to": "Bayleef",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 153,
    "from": "Bayleef",
    "toId": 154,
    "to": "Meganium",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 32
      }
    ]
  },
  {
    "fromId": 155,
    "from": "Cyndaquil",
    "toId": 156,
    "to": "Quilava",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 14
      },
      {
        "trigger": "level-up",
        "minLevel": 17
      }
    ]
  },
  {
    "fromId": 156,
    "from": "Quilava",
    "toId": 157,
    "to": "Typhlosion",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      },
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 158,
    "from": "Totodile",
    "toId": 159,
    "to": "Croconaw",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 18
      }
    ]
  },
  {
    "fromId": 159,
    "from": "Croconaw",
    "toId": 160,
    "to": "Feraligatr",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 161,
    "from": "Sentret",
    "toId": 162,
    "to": "Furret",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 15
      }
    ]
  },
  {
    "fromId": 163,
    "from": "Hoothoot",
    "toId": 164,
    "to": "Noctowl",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 165,
    "from": "Ledyba",
    "toId": 166,
    "to": "Ledian",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 18
      }
    ]
  },
  {
    "fromId": 167,
    "from": "Spinarak",
    "toId": 168,
    "to": "Ariados",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 22
      }
    ]
  },
  {
    "fromId": 170,
    "from": "Chinchou",
    "toId": 171,
    "to": "Lanturn",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 27
      }
    ]
  },
  {
    "fromId": 172,
    "from": "Pichu",
    "toId": 25,
    "to": "Pikachu",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 220
      }
    ]
  },
  {
    "fromId": 173,
    "from": "Cleffa",
    "toId": 35,
    "to": "Clefairy",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 160
      }
    ]
  },
  {
    "fromId": 174,
    "from": "Igglybuff",
    "toId": 39,
    "to": "Jigglypuff",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 160
      }
    ]
  },
  {
    "fromId": 175,
    "from": "Togepi",
    "toId": 176,
    "to": "Togetic",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 160
      }
    ]
  },
  {
    "fromId": 177,
    "from": "Natu",
    "toId": 178,
    "to": "Xatu",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 25
      }
    ]
  },
  {
    "fromId": 179,
    "from": "Mareep",
    "toId": 180,
    "to": "Flaaffy",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 15
      }
    ]
  },
  {
    "fromId": 180,
    "from": "Flaaffy",
    "toId": 181,
    "to": "Ampharos",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 183,
    "from": "Marill",
    "toId": 184,
    "to": "Azumarill",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 18
      }
    ]
  },
  {
    "fromId": 187,
    "from": "Hoppip",
    "toId": 188,
    "to": "Skiploom",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 18
      }
    ]
  },
  {
    "fromId": 188,
    "from": "Skiploom",
    "toId": 189,
    "to": "Jumpluff",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 27
      }
    ]
  },
  {
    "fromId": 191,
    "from": "Sunkern",
    "toId": 192,
    "to": "Sunflora",
    "details": [
      {
        "trigger": "use-item",
        "item": "sun-stone"
      }
    ]
  },
  {
    "fromId": 194,
    "from": "Wooper",
    "toId": 195,
    "to": "Quagsire",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 204,
    "from": "Pineco",
    "toId": 205,
    "to": "Forretress",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 31
      }
    ]
  },
  {
    "fromId": 209,
    "from": "Snubbull",
    "toId": 210,
    "to": "Granbull",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 23
      }
    ]
  },
  {
    "fromId": 216,
    "from": "Teddiursa",
    "toId": 217,
    "to": "Ursaring",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 218,
    "from": "Slugma",
    "toId": 219,
    "to": "Magcargo",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 38
      }
    ]
  },
  {
    "fromId": 220,
    "from": "Swinub",
    "toId": 221,
    "to": "Piloswine",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 33
      }
    ]
  },
  {
    "fromId": 223,
    "from": "Remoraid",
    "toId": 224,
    "to": "Octillery",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 25
      }
    ]
  },
  {
    "fromId": 228,
    "from": "Houndour",
    "toId": 229,
    "to": "Houndoom",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 24
      }
    ]
  },
  {
    "fromId": 231,
    "from": "Phanpy",
    "toId": 232,
    "to": "Donphan",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 25
      }
    ]
  },
  {
    "fromId": 236,
    "from": "Tyrogue",
    "toId": 106,
    "to": "Hitmonlee",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20,
        "relativePhysicalStats": 1
      }
    ]
  },
  {
    "fromId": 236,
    "from": "Tyrogue",
    "toId": 107,
    "to": "Hitmonchan",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20,
        "relativePhysicalStats": -1
      }
    ]
  },
  {
    "fromId": 236,
    "from": "Tyrogue",
    "toId": 237,
    "to": "Hitmontop",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20,
        "relativePhysicalStats": 0
      }
    ]
  },
  {
    "fromId": 238,
    "from": "Smoochum",
    "toId": 124,
    "to": "Jynx",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 239,
    "from": "Elekid",
    "toId": 125,
    "to": "Electabuzz",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 240,
    "from": "Magby",
    "toId": 126,
    "to": "Magmar",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 246,
    "from": "Larvitar",
    "toId": 247,
    "to": "Pupitar",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 247,
    "from": "Pupitar",
    "toId": 248,
    "to": "Tyranitar",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 55
      }
    ]
  },
  {
    "fromId": 252,
    "from": "Treecko",
    "toId": 253,
    "to": "Grovyle",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 253,
    "from": "Grovyle",
    "toId": 254,
    "to": "Sceptile",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 255,
    "from": "Torchic",
    "toId": 256,
    "to": "Combusken",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 256,
    "from": "Combusken",
    "toId": 257,
    "to": "Blaziken",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 258,
    "from": "Mudkip",
    "toId": 259,
    "to": "Marshtomp",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 16
      }
    ]
  },
  {
    "fromId": 259,
    "from": "Marshtomp",
    "toId": 260,
    "to": "Swampert",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 261,
    "from": "Poochyena",
    "toId": 262,
    "to": "Mightyena",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 18
      }
    ]
  },
  {
    "fromId": 263,
    "from": "Zigzagoon",
    "toId": 264,
    "to": "Linoone",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      },
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 265,
    "from": "Wurmple",
    "toId": 266,
    "to": "Silcoon",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 7
      }
    ]
  },
  {
    "fromId": 265,
    "from": "Wurmple",
    "toId": 268,
    "to": "Cascoon",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 7
      }
    ]
  },
  {
    "fromId": 266,
    "from": "Silcoon",
    "toId": 267,
    "to": "Beautifly",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 10
      }
    ]
  },
  {
    "fromId": 268,
    "from": "Cascoon",
    "toId": 269,
    "to": "Dustox",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 10
      }
    ]
  },
  {
    "fromId": 270,
    "from": "Lotad",
    "toId": 271,
    "to": "Lombre",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 14
      }
    ]
  },
  {
    "fromId": 271,
    "from": "Lombre",
    "toId": 272,
    "to": "Ludicolo",
    "details": [
      {
        "trigger": "use-item",
        "item": "water-stone"
      }
    ]
  },
  {
    "fromId": 273,
    "from": "Seedot",
    "toId": 274,
    "to": "Nuzleaf",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 14
      }
    ]
  },
  {
    "fromId": 274,
    "from": "Nuzleaf",
    "toId": 275,
    "to": "Shiftry",
    "details": [
      {
        "trigger": "use-item",
        "item": "leaf-stone"
      }
    ]
  },
  {
    "fromId": 276,
    "from": "Taillow",
    "toId": 277,
    "to": "Swellow",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 22
      }
    ]
  },
  {
    "fromId": 278,
    "from": "Wingull",
    "toId": 279,
    "to": "Pelipper",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 25
      }
    ]
  },
  {
    "fromId": 280,
    "from": "Ralts",
    "toId": 281,
    "to": "Kirlia",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 281,
    "from": "Kirlia",
    "toId": 282,
    "to": "Gardevoir",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 283,
    "from": "Surskit",
    "toId": 284,
    "to": "Masquerain",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 22
      }
    ]
  },
  {
    "fromId": 285,
    "from": "Shroomish",
    "toId": 286,
    "to": "Breloom",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 23
      }
    ]
  },
  {
    "fromId": 287,
    "from": "Slakoth",
    "toId": 288,
    "to": "Vigoroth",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 18
      }
    ]
  },
  {
    "fromId": 288,
    "from": "Vigoroth",
    "toId": 289,
    "to": "Slaking",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 290,
    "from": "Nincada",
    "toId": 291,
    "to": "Ninjask",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 290,
    "from": "Nincada",
    "toId": 292,
    "to": "Shedinja",
    "details": [
      {
        "trigger": "shed"
      }
    ]
  },
  {
    "fromId": 293,
    "from": "Whismur",
    "toId": 294,
    "to": "Loudred",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 294,
    "from": "Loudred",
    "toId": 295,
    "to": "Exploud",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 40
      }
    ]
  },
  {
    "fromId": 296,
    "from": "Makuhita",
    "toId": 297,
    "to": "Hariyama",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 24
      }
    ]
  },
  {
    "fromId": 298,
    "from": "Azurill",
    "toId": 183,
    "to": "Marill",
    "details": [
      {
        "trigger": "level-up",
        "minHappiness": 160
      }
    ]
  },
  {
    "fromId": 300,
    "from": "Skitty",
    "toId": 301,
    "to": "Delcatty",
    "details": [
      {
        "trigger": "use-item",
        "item": "moon-stone"
      }
    ]
  },
  {
    "fromId": 304,
    "from": "Aron",
    "toId": 305,
    "to": "Lairon",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 32
      }
    ]
  },
  {
    "fromId": 305,
    "from": "Lairon",
    "toId": 306,
    "to": "Aggron",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 42
      }
    ]
  },
  {
    "fromId": 307,
    "from": "Meditite",
    "toId": 308,
    "to": "Medicham",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 37
      }
    ]
  },
  {
    "fromId": 309,
    "from": "Electrike",
    "toId": 310,
    "to": "Manectric",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 26
      }
    ]
  },
  {
    "fromId": 316,
    "from": "Gulpin",
    "toId": 317,
    "to": "Swalot",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 26
      }
    ]
  },
  {
    "fromId": 318,
    "from": "Carvanha",
    "toId": 319,
    "to": "Sharpedo",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 320,
    "from": "Wailmer",
    "toId": 321,
    "to": "Wailord",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 40
      }
    ]
  },
  {
    "fromId": 322,
    "from": "Numel",
    "toId": 323,
    "to": "Camerupt",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 33
      }
    ]
  },
  {
    "fromId": 325,
    "from": "Spoink",
    "toId": 326,
    "to": "Grumpig",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 32
      }
    ]
  },
  {
    "fromId": 328,
    "from": "Trapinch",
    "toId": 329,
    "to": "Vibrava",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 35
      }
    ]
  },
  {
    "fromId": 329,
    "from": "Vibrava",
    "toId": 330,
    "to": "Flygon",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 45
      }
    ]
  },
  {
    "fromId": 331,
    "from": "Cacnea",
    "toId": 332,
    "to": "Cacturne",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 32
      }
    ]
  },
  {
    "fromId": 333,
    "from": "Swablu",
    "toId": 334,
    "to": "Altaria",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 35
      }
    ]
  },
  {
    "fromId": 339,
    "from": "Barboach",
    "toId": 340,
    "to": "Whiscash",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 341,
    "from": "Corphish",
    "toId": 342,
    "to": "Crawdaunt",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 343,
    "from": "Baltoy",
    "toId": 344,
    "to": "Claydol",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 36
      }
    ]
  },
  {
    "fromId": 345,
    "from": "Lileep",
    "toId": 346,
    "to": "Cradily",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 40
      }
    ]
  },
  {
    "fromId": 347,
    "from": "Anorith",
    "toId": 348,
    "to": "Armaldo",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 40
      }
    ]
  },
  {
    "fromId": 349,
    "from": "Feebas",
    "toId": 350,
    "to": "Milotic",
    "details": [
      {
        "trigger": "level-up",
        "minBeauty": 170
      },
      {
        "trigger": "trade",
        "heldItem": "prism-scale"
      }
    ]
  },
  {
    "fromId": 353,
    "from": "Shuppet",
    "toId": 354,
    "to": "Banette",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 37
      }
    ]
  },
  {
    "fromId": 355,
    "from": "Duskull",
    "toId": 356,
    "to": "Dusclops",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 37
      }
    ]
  },
  {
    "fromId": 360,
    "from": "Wynaut",
    "toId": 202,
    "to": "Wobbuffet",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 15
      }
    ]
  },
  {
    "fromId": 361,
    "from": "Snorunt",
    "toId": 362,
    "to": "Glalie",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 42
      }
    ]
  },
  {
    "fromId": 363,
    "from": "Spheal",
    "toId": 364,
    "to": "Sealeo",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 32
      }
    ]
  },
  {
    "fromId": 364,
    "from": "Sealeo",
    "toId": 365,
    "to": "Walrein",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 44
      }
    ]
  },
  {
    "fromId": 366,
    "from": "Clamperl",
    "toId": 367,
    "to": "Huntail",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "deep-sea-tooth"
      }
    ]
  },
  {
    "fromId": 366,
    "from": "Clamperl",
    "toId": 368,
    "to": "Gorebyss",
    "details": [
      {
        "trigger": "trade",
        "heldItem": "deep-sea-scale"
      }
    ]
  },
  {
    "fromId": 371,
    "from": "Bagon",
    "toId": 372,
    "to": "Shelgon",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 30
      }
    ]
  },
  {
    "fromId": 372,
    "from": "Shelgon",
    "toId": 373,
    "to": "Salamence",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 50
      }
    ]
  },
  {
    "fromId": 374,
    "from": "Beldum",
    "toId": 375,
    "to": "Metang",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 20
      }
    ]
  },
  {
    "fromId": 375,
    "from": "Metang",
    "toId": 376,
    "to": "Metagross",
    "details": [
      {
        "trigger": "level-up",
        "minLevel": 45
      }
    ]
  }
];
