// Generated by scripts/generate-pokemon-knowledge.mjs.
// Source manifests: lib/pokemon/knowledge/sources/*.json.
// Do not edit this file by hand; update the source manifests and rerun the generator.

import { POKEMON_KNOWLEDGE_SOURCES, type PokemonKnowledgeSource } from "./provenance";

export interface ItemIdRange {
  generation: 1 | 2 | 3;
  label: string;
  start: number;
  end: number;
  source: PokemonKnowledgeSource;
}

export const ITEM_ID_RANGES = {
  gen1Hms: {
    generation: 1,
    label: "HM01-HM05",
    start: 0xc4,
    end: 0xc8,
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokered,
  },
  gen1Tms: {
    generation: 1,
    label: "TM01-TM50",
    start: 0xc9,
    end: 0xfa,
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokered,
  },
  gen2Tms: {
    generation: 2,
    label: "TM01-TM50",
    start: 0xbf,
    end: 0xf2,
    source: POKEMON_KNOWLEDGE_SOURCES.pokecrystal,
  },
  gen2Hms: {
    generation: 2,
    label: "HM01-HM07",
    start: 0xf3,
    end: 0xf9,
    source: POKEMON_KNOWLEDGE_SOURCES.pokecrystal,
  },
} satisfies Record<string, ItemIdRange>;

export const GEN1_HM_MOVES = [
  "Cut",
  "Fly",
  "Surf",
  "Strength",
  "Flash",
] as const;

export const GEN1_TM_MOVES = [
  "Mega Punch",
  "Razor Wind",
  "Swords Dance",
  "Whirlwind",
  "Mega Kick",
  "Toxic",
  "Horn Drill",
  "Body Slam",
  "Take Down",
  "Double-Edge",
  "Bubble Beam",
  "Water Gun",
  "Ice Beam",
  "Blizzard",
  "Hyper Beam",
  "Pay Day",
  "Submission",
  "Counter",
  "Seismic Toss",
  "Rage",
  "Mega Drain",
  "Solar Beam",
  "Dragon Rage",
  "Thunderbolt",
  "Thunder",
  "Earthquake",
  "Fissure",
  "Dig",
  "Psychic",
  "Teleport",
  "Mimic",
  "Double Team",
  "Reflect",
  "Bide",
  "Metronome",
  "Self-Destruct",
  "Egg Bomb",
  "Fire Blast",
  "Swift",
  "Skull Bash",
  "Soft-Boiled",
  "Dream Eater",
  "Sky Attack",
  "Rest",
  "Thunder Wave",
  "Psywave",
  "Explosion",
  "Rock Slide",
  "Tri Attack",
  "Substitute",
] as const;

export function getGen1MachineItemName(id: number): string | undefined {
  const hmRange = ITEM_ID_RANGES.gen1Hms;
  if (id >= hmRange.start && id <= hmRange.end) {
    const number = id - hmRange.start + 1;
    return `HM${String(number).padStart(2, "0")} ${GEN1_HM_MOVES[number - 1]}`;
  }

  const tmRange = ITEM_ID_RANGES.gen1Tms;
  if (id >= tmRange.start && id <= tmRange.end) {
    const number = id - tmRange.start + 1;
    return `TM${String(number).padStart(2, "0")} ${GEN1_TM_MOVES[number - 1]}`;
  }

  return undefined;
}
