// Generated by scripts/generate-pokemon-knowledge.mjs.
// Source manifests: lib/pokemon/knowledge/sources/*.json.
// Do not edit this file by hand; update the source manifests and rerun the generator.

import { POKEMON_KNOWLEDGE_SOURCES, type PokemonKnowledgeSource } from "./provenance";

export interface Gen1SaveLayout {
  generation: 1;
  gameProfile: string;
  source: PokemonKnowledgeSource;
  liveWramSource?: PokemonKnowledgeSource;
  boxOffsetsSource?: PokemonKnowledgeSource;
  offsets: {
    playerName: number;
    rivalName: number;
    money: number;
    badges: number;
    currentMap: number;
    playTimeHours: number;
    playTimeMinutes: number;
    playTimeSeconds: number;
    partyCount: number;
    partySpecies: number;
    partyData: number;
    trainerId: number;
    pokedexOwned: number;
    pokedexSeen: number;
    playerStarter: number;
    oaksLabScript: number;
    hallOfFameCount: number;
    currentBoxNumber: number;
    currentBoxData: number;
  };
  boxOffsets: number[];
  liveWramOffsets: Record<string, number>;
}

export interface Gen2SaveLayout {
  generation: 2;
  gameProfile: string;
  source: PokemonKnowledgeSource;
  liveWramSource?: PokemonKnowledgeSource;
  boxOffsetsSource?: PokemonKnowledgeSource;
  offsets: {
    playerGender: number;
    playerName: number;
    trainerId: number;
    money: number;
    badgesJohto: number;
    badgesKanto: number;
    playTime: number;
    partyCount: number;
    partySpecies: number;
    partyData: number;
    currentMapGroup: number;
    currentMap: number;
    currentMapX: number;
    currentMapY: number;
    elmsLabScene: number;
    radioTower5FScene: number;
    teamRocketBaseB2FScene: number;
    teamRocketBaseB3FScene: number;
    currentBoxNumber: number;
    boxNames: number;
    currentBoxData: number;
  };
  boxOffsets: number[];
  liveWramOffsets: Record<string, number>;
}

export interface Gen3SaveLayout {
  generation: 3;
  gameProfile: string;
  source: PokemonKnowledgeSource;
  offsets: {
    trainerName: number;
    trainerGender: number;
    trainerId: number;
    playTimeHours: number;
    playTimeMinutes: number;
    playTimeSeconds: number;
    playTimeVBlanks?: number;
    encryptionKey?: number;
    pokedexMode: number;
    pokedexNationalMagic: number;
    location: number;
    locationMapGroup: number;
    locationMapNum: number;
    partyCount: number;
    party: number;
    money: number;
    coins: number;
    registeredItem: number;
    pcItems: number;
    pokedexOwned: number;
    pokedexSeen: number;
    pokedexSeen1: number;
    pokedexSeen2: number;
    flags: number;
    vars: number;
    badgeFlagStart: number;
    boxCurrent: number;
    boxData: number;
    boxNames: number;
    boxWallpapers: number;
  };
  sectionIds: {
    trainerInfo: number;
    teamItems: number;
    gameState: number;
    pcBufferStart: number;
    pcBufferEnd: number;
  };
  partyCountSize: 1 | 4;
  quantityMask: "none" | "security-key-low16";
  pcBoxCount: number;
  pcBoxCapacity: number;
  pcPokemonSize: number;
  partyPokemonSize: number;
  boxNameLength: number;
}

export const GEN1_SAVE_LAYOUTS = {
  redBlue: {
    generation: 1,
    gameProfile: "red-blue-en",
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokered,
    liveWramSource: POKEMON_KNOWLEDGE_SOURCES.dataCrystalRedBlueRamMap,
    boxOffsetsSource: POKEMON_KNOWLEDGE_SOURCES.dataCrystalRedBlueRamMap,
    offsets: {
      playerName: 0x2598,
      rivalName: 0x25f6,
      money: 0x25f3,
      badges: 0x2602,
      currentMap: 0x260a,
      playTimeHours: 0x2ced,
      playTimeMinutes: 0x2cef,
      playTimeSeconds: 0x2cf0,
      partyCount: 0x2f2c,
      partySpecies: 0x2f2d,
      partyData: 0x2f34,
      trainerId: 0x2605,
      pokedexOwned: 0x25a3,
      pokedexSeen: 0x25b6,
      playerStarter: 0x29c3,
      oaksLabScript: 0x28a2,
      hallOfFameCount: 0x284e,
      currentBoxNumber: 0x284c,
      currentBoxData: 0x30c0,
    },
    boxOffsets: [
      0x4000,
      0x4462,
      0x48c4,
      0x4d26,
      0x5188,
      0x55ea,
      0x6000,
      0x6462,
      0x68c4,
      0x6d26,
      0x7188,
      0x75ea,
    ],
    liveWramOffsets: {
      playerName: 0xd158,
      trainerId: 0xd359,
      money: 0xd347,
      badges: 0xd356,
      currentMap: 0xd35e,
      playTimeHours: 0xda41,
      playTimeMinutes: 0xda43,
      playTimeSeconds: 0xda44,
      partyCount: 0xd163,
      partySpecies: 0xd164,
      partyData: 0xd16b,
      partyOtNames: 0xd273,
      partyNicknames: 0xd2b5,
      pokedexOwned: 0xd2f7,
      pokedexSeen: 0xd30a,
      playerStarter: 0xd717,
      oaksLabScript: 0xd5f6,
      hallOfFameCount: 0xd5a2,
      numItems: 0xd31d,
      items: 0xd31e,
      numPcItems: 0xd53a,
      pcItems: 0xd53b,
      currentBoxNumber: 0xd5a0,
      currentBoxData: 0xda80,
    },
  },
  yellow: {
    generation: 1,
    gameProfile: "yellow-en",
    source: POKEMON_KNOWLEDGE_SOURCES.bulbapediaGen1Save,
    liveWramSource: POKEMON_KNOWLEDGE_SOURCES.dataCrystalYellowRamMap,
    boxOffsetsSource: POKEMON_KNOWLEDGE_SOURCES.bulbapediaGen1PokemonData,
    offsets: {
      playerName: 0x2598,
      rivalName: 0x25f6,
      money: 0x25f3,
      badges: 0x2602,
      currentMap: 0x260a,
      playTimeHours: 0x2ced,
      playTimeMinutes: 0x2cef,
      playTimeSeconds: 0x2cf0,
      partyCount: 0x2f2c,
      partySpecies: 0x2f2d,
      partyData: 0x2f34,
      trainerId: 0x2605,
      pokedexOwned: 0x25a3,
      pokedexSeen: 0x25b6,
      playerStarter: 0x29c3,
      oaksLabScript: 0x28a1,
      hallOfFameCount: 0x284e,
      currentBoxNumber: 0x284c,
      currentBoxData: 0x30c0,
    },
    boxOffsets: [
      0x4000,
      0x4462,
      0x48c4,
      0x4d26,
      0x5188,
      0x55ea,
      0x6000,
      0x6462,
      0x68c4,
      0x6d26,
      0x7188,
      0x75ea,
    ],
    liveWramOffsets: {
      playerName: 0xd157,
      trainerId: 0xd358,
      money: 0xd346,
      badges: 0xd355,
      currentMap: 0xd35d,
      playTimeHours: 0xda40,
      playTimeMinutes: 0xda42,
      playTimeSeconds: 0xda43,
      partyCount: 0xd162,
      partySpecies: 0xd163,
      partyData: 0xd16a,
      partyOtNames: 0xd272,
      partyNicknames: 0xd2b4,
      pokedexOwned: 0xd2f6,
      pokedexSeen: 0xd309,
      playerStarter: 0xd716,
      oaksLabScript: 0xd5f4,
      hallOfFameCount: 0xd5a1,
      numItems: 0xd31c,
      items: 0xd31d,
      numPcItems: 0xd539,
      pcItems: 0xd53a,
      currentBoxNumber: 0xd59f,
      currentBoxData: 0xda94,
    },
  },
} satisfies Record<string, Gen1SaveLayout>;

export const GEN2_SAVE_LAYOUTS = {
  goldSilver: {
    generation: 2,
    gameProfile: "gold-silver-en",
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokegold,
    liveWramSource: POKEMON_KNOWLEDGE_SOURCES.pretPokegold,
    boxOffsetsSource: POKEMON_KNOWLEDGE_SOURCES.pretPokegold,
    offsets: {
      playerGender: -1,
      playerName: 0x200b,
      trainerId: 0x2009,
      money: 0x23db,
      badgesJohto: 0x23e4,
      badgesKanto: 0x23e5,
      playTime: 0x2053,
      partyCount: 0x288a,
      partySpecies: 0x288b,
      partyData: 0x2892,
      currentMapGroup: 0x2868,
      currentMap: 0x2869,
      currentMapX: 0x286a,
      currentMapY: 0x286b,
      elmsLabScene: 0x2534,
      radioTower5FScene: 0x2549,
      teamRocketBaseB2FScene: 0x254f,
      teamRocketBaseB3FScene: 0x2550,
      currentBoxNumber: 0x2724,
      boxNames: 0x2727,
      currentBoxData: 0x2d6c,
    },
    boxOffsets: [
      0x4000,
      0x4450,
      0x48a0,
      0x4cf0,
      0x5140,
      0x5590,
      0x59e0,
      0x6000,
      0x6450,
      0x68a0,
      0x6cf0,
      0x7140,
      0x7590,
      0x79e0,
    ],
    liveWramOffsets: {
      trainerId: 0xd1a1,
      trainerName: 0xd1a3,
      playTime: 0xd1eb,
      money: 0xd573,
      johtoBadges: 0xd57c,
      kantoBadges: 0xd57d,
      tmsHms: 0xd57e,
      numItems: 0xd5b7,
      items: 0xd5b8,
      numKeyItems: 0xd5e1,
      keyItems: 0xd5e2,
      numBalls: 0xd5fc,
      balls: 0xd5fd,
      pcStorage: 0x247e,
      mapGroup: 0xda00,
      mapNumber: 0xda01,
      playerX: 0xda02,
      playerY: 0xda03,
      elmsLabScene: 0xd6cc,
      radioTower5FScene: 0xd6e1,
      teamRocketBaseB2FScene: 0xd6e7,
      teamRocketBaseB3FScene: 0xd6e8,
      partyCount: 0xda22,
      partyMon1: 0xda2a,
      partyNicknames: 0xdb8c,
    },
  },
  crystal: {
    generation: 2,
    gameProfile: "crystal-en",
    source: POKEMON_KNOWLEDGE_SOURCES.pokecrystal,
    liveWramSource: POKEMON_KNOWLEDGE_SOURCES.pokecrystal,
    boxOffsetsSource: POKEMON_KNOWLEDGE_SOURCES.pokecrystal,
    offsets: {
      playerGender: 0x3e3d,
      playerName: 0x200b,
      trainerId: 0x2009,
      money: 0x23dc,
      badgesJohto: 0x23e5,
      badgesKanto: 0x23e6,
      playTime: 0x2053,
      partyCount: 0x2865,
      partySpecies: 0x2866,
      partyData: 0x286d,
      currentMapGroup: 0x2843,
      currentMap: 0x2844,
      currentMapX: 0x2845,
      currentMapY: 0x2846,
      elmsLabScene: 0x2515,
      radioTower5FScene: 0x2537,
      teamRocketBaseB2FScene: 0x2541,
      teamRocketBaseB3FScene: 0x2542,
      currentBoxNumber: 0x2700,
      boxNames: 0x2703,
      currentBoxData: 0x2d10,
    },
    boxOffsets: [
      0x4000,
      0x4450,
      0x48a0,
      0x4cf0,
      0x5140,
      0x5590,
      0x59e0,
      0x6000,
      0x6450,
      0x68a0,
      0x6cf0,
      0x7140,
      0x7590,
      0x79e0,
    ],
    liveWramOffsets: {
      playerGender: 0xd472,
      trainerId: 0xd47b,
      trainerName: 0xd47d,
      playTime: 0xd4c4,
      money: 0xd84e,
      johtoBadges: 0xd857,
      kantoBadges: 0xd858,
      tmsHms: 0xd859,
      numItems: 0xd892,
      items: 0xd893,
      numKeyItems: 0xd8bc,
      keyItems: 0xd8bd,
      numBalls: 0xd8d7,
      balls: 0xd8d8,
      pcStorage: 0x247f,
      mapGroup: 0xdcb5,
      mapNumber: 0xdcb6,
      playerY: 0xdcb7,
      playerX: 0xdcb8,
      elmsLabScene: 0xd987,
      radioTower5FScene: 0xd9a9,
      teamRocketBaseB2FScene: 0xd9b3,
      teamRocketBaseB3FScene: 0xd9b4,
      partyCount: 0xdcd7,
      partyMon1: 0xdcdf,
      partyNicknames: 0xde41,
    },
  },
} satisfies Record<string, Gen2SaveLayout>;

export const GEN3_SAVE_LAYOUTS = {
  rubySapphire: {
    generation: 3,
    gameProfile: "ruby-sapphire-en",
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokeruby,
    offsets: {
      trainerName: 0x0000,
      trainerGender: 0x0008,
      trainerId: 0x000a,
      playTimeHours: 0x000e,
      playTimeMinutes: 0x0010,
      playTimeSeconds: 0x0011,
      playTimeVBlanks: 0x0012,
      pokedexMode: 0x0019,
      pokedexNationalMagic: 0x001a,
      location: 0x0004,
      locationMapGroup: 0x0004,
      locationMapNum: 0x0005,
      partyCount: 0x0234,
      party: 0x0238,
      money: 0x0490,
      coins: 0x0494,
      registeredItem: 0x0496,
      pcItems: 0x0498,
      pokedexOwned: 0x0028,
      pokedexSeen: 0x005c,
      pokedexSeen1: 0x0938,
      pokedexSeen2: 0x3a8c,
      flags: 0x1220,
      vars: 0x1340,
      badgeFlagStart: 0x0807,
      boxCurrent: 0x0000,
      boxData: 0x0004,
      boxNames: 0x8344,
      boxWallpapers: 0x83c2,
    },
    sectionIds: {
      trainerInfo: 0,
      teamItems: 1,
      gameState: 2,
      pcBufferStart: 5,
      pcBufferEnd: 13,
    },
    partyCountSize: 1,
    quantityMask: "none",
    pcBoxCount: 14,
    pcBoxCapacity: 30,
    pcPokemonSize: 80,
    partyPokemonSize: 100,
    boxNameLength: 9,
  },
  emerald: {
    generation: 3,
    gameProfile: "emerald-en",
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokeemerald,
    offsets: {
      trainerName: 0x0000,
      trainerGender: 0x0008,
      trainerId: 0x000a,
      playTimeHours: 0x000e,
      playTimeMinutes: 0x0010,
      playTimeSeconds: 0x0011,
      playTimeVBlanks: 0x0012,
      encryptionKey: 0x00ac,
      pokedexMode: 0x0019,
      pokedexNationalMagic: 0x001a,
      location: 0x0004,
      locationMapGroup: 0x0004,
      locationMapNum: 0x0005,
      partyCount: 0x0234,
      party: 0x0238,
      money: 0x0490,
      coins: 0x0494,
      registeredItem: 0x0496,
      pcItems: 0x0498,
      pokedexOwned: 0x0028,
      pokedexSeen: 0x005c,
      pokedexSeen1: 0x0988,
      pokedexSeen2: 0x3b24,
      flags: 0x1270,
      vars: 0x139c,
      badgeFlagStart: 0x0867,
      boxCurrent: 0x0000,
      boxData: 0x0004,
      boxNames: 0x8344,
      boxWallpapers: 0x83c2,
    },
    sectionIds: {
      trainerInfo: 0,
      teamItems: 1,
      gameState: 2,
      pcBufferStart: 5,
      pcBufferEnd: 13,
    },
    partyCountSize: 1,
    quantityMask: "security-key-low16",
    pcBoxCount: 14,
    pcBoxCapacity: 30,
    pcPokemonSize: 80,
    partyPokemonSize: 100,
    boxNameLength: 9,
  },
  fireRedLeafGreen: {
    generation: 3,
    gameProfile: "firered-leafgreen-en",
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokefirered,
    offsets: {
      trainerName: 0x0000,
      trainerGender: 0x0008,
      trainerId: 0x000a,
      playTimeHours: 0x000e,
      playTimeMinutes: 0x0010,
      playTimeSeconds: 0x0011,
      playTimeVBlanks: 0x0012,
      encryptionKey: 0x0f20,
      pokedexMode: 0x0019,
      pokedexNationalMagic: 0x001b,
      location: 0x0004,
      locationMapGroup: 0x0004,
      locationMapNum: 0x0005,
      partyCount: 0x0034,
      party: 0x0038,
      money: 0x0290,
      coins: 0x0294,
      registeredItem: 0x0296,
      pcItems: 0x0298,
      pokedexOwned: 0x0028,
      pokedexSeen: 0x005c,
      pokedexSeen1: 0x05f8,
      pokedexSeen2: 0x3a18,
      flags: 0x0ee0,
      vars: 0x1000,
      badgeFlagStart: 0x0820,
      boxCurrent: 0x0000,
      boxData: 0x0004,
      boxNames: 0x8344,
      boxWallpapers: 0x83c2,
    },
    sectionIds: {
      trainerInfo: 0,
      teamItems: 1,
      gameState: 2,
      pcBufferStart: 5,
      pcBufferEnd: 13,
    },
    partyCountSize: 1,
    quantityMask: "security-key-low16",
    pcBoxCount: 14,
    pcBoxCapacity: 30,
    pcPokemonSize: 80,
    partyPokemonSize: 100,
    boxNameLength: 9,
  },
} satisfies Record<string, Gen3SaveLayout>;
