// Generated by scripts/generate-pokemon-knowledge.mjs.
// Source manifests: lib/pokemon/knowledge/sources/*.json.
// Do not edit this file by hand; update the source manifests and rerun the generator.

import { POKEMON_KNOWLEDGE_SOURCES, type PokemonKnowledgeSource } from "./provenance";

export interface SpeciesIdMapEntry {
  internal: number;
  national: number;
}

export interface SpeciesIdMap {
  generation: 3;
  gameProfile: string;
  source: PokemonKnowledgeSource;
  oldUnownInternalStart: number;
  oldUnownInternalEnd: number;
  oldUnownNational: number;
  entries: SpeciesIdMapEntry[];
}

export const GEN3_SPECIES_ID_MAPS = {
  emerald: {
    generation: 3,
    gameProfile: "gen3-internal-species-en",
    source: POKEMON_KNOWLEDGE_SOURCES.pretPokeemerald,
    oldUnownInternalStart: 252,
    oldUnownInternalEnd: 276,
    oldUnownNational: 201,
    entries: [
      {
        internal: 1,
        national: 1,
      },
      {
        internal: 2,
        national: 2,
      },
      {
        internal: 3,
        national: 3,
      },
      {
        internal: 4,
        national: 4,
      },
      {
        internal: 5,
        national: 5,
      },
      {
        internal: 6,
        national: 6,
      },
      {
        internal: 7,
        national: 7,
      },
      {
        internal: 8,
        national: 8,
      },
      {
        internal: 9,
        national: 9,
      },
      {
        internal: 10,
        national: 10,
      },
      {
        internal: 11,
        national: 11,
      },
      {
        internal: 12,
        national: 12,
      },
      {
        internal: 13,
        national: 13,
      },
      {
        internal: 14,
        national: 14,
      },
      {
        internal: 15,
        national: 15,
      },
      {
        internal: 16,
        national: 16,
      },
      {
        internal: 17,
        national: 17,
      },
      {
        internal: 18,
        national: 18,
      },
      {
        internal: 19,
        national: 19,
      },
      {
        internal: 20,
        national: 20,
      },
      {
        internal: 21,
        national: 21,
      },
      {
        internal: 22,
        national: 22,
      },
      {
        internal: 23,
        national: 23,
      },
      {
        internal: 24,
        national: 24,
      },
      {
        internal: 25,
        national: 25,
      },
      {
        internal: 26,
        national: 26,
      },
      {
        internal: 27,
        national: 27,
      },
      {
        internal: 28,
        national: 28,
      },
      {
        internal: 29,
        national: 29,
      },
      {
        internal: 30,
        national: 30,
      },
      {
        internal: 31,
        national: 31,
      },
      {
        internal: 32,
        national: 32,
      },
      {
        internal: 33,
        national: 33,
      },
      {
        internal: 34,
        national: 34,
      },
      {
        internal: 35,
        national: 35,
      },
      {
        internal: 36,
        national: 36,
      },
      {
        internal: 37,
        national: 37,
      },
      {
        internal: 38,
        national: 38,
      },
      {
        internal: 39,
        national: 39,
      },
      {
        internal: 40,
        national: 40,
      },
      {
        internal: 41,
        national: 41,
      },
      {
        internal: 42,
        national: 42,
      },
      {
        internal: 43,
        national: 43,
      },
      {
        internal: 44,
        national: 44,
      },
      {
        internal: 45,
        national: 45,
      },
      {
        internal: 46,
        national: 46,
      },
      {
        internal: 47,
        national: 47,
      },
      {
        internal: 48,
        national: 48,
      },
      {
        internal: 49,
        national: 49,
      },
      {
        internal: 50,
        national: 50,
      },
      {
        internal: 51,
        national: 51,
      },
      {
        internal: 52,
        national: 52,
      },
      {
        internal: 53,
        national: 53,
      },
      {
        internal: 54,
        national: 54,
      },
      {
        internal: 55,
        national: 55,
      },
      {
        internal: 56,
        national: 56,
      },
      {
        internal: 57,
        national: 57,
      },
      {
        internal: 58,
        national: 58,
      },
      {
        internal: 59,
        national: 59,
      },
      {
        internal: 60,
        national: 60,
      },
      {
        internal: 61,
        national: 61,
      },
      {
        internal: 62,
        national: 62,
      },
      {
        internal: 63,
        national: 63,
      },
      {
        internal: 64,
        national: 64,
      },
      {
        internal: 65,
        national: 65,
      },
      {
        internal: 66,
        national: 66,
      },
      {
        internal: 67,
        national: 67,
      },
      {
        internal: 68,
        national: 68,
      },
      {
        internal: 69,
        national: 69,
      },
      {
        internal: 70,
        national: 70,
      },
      {
        internal: 71,
        national: 71,
      },
      {
        internal: 72,
        national: 72,
      },
      {
        internal: 73,
        national: 73,
      },
      {
        internal: 74,
        national: 74,
      },
      {
        internal: 75,
        national: 75,
      },
      {
        internal: 76,
        national: 76,
      },
      {
        internal: 77,
        national: 77,
      },
      {
        internal: 78,
        national: 78,
      },
      {
        internal: 79,
        national: 79,
      },
      {
        internal: 80,
        national: 80,
      },
      {
        internal: 81,
        national: 81,
      },
      {
        internal: 82,
        national: 82,
      },
      {
        internal: 83,
        national: 83,
      },
      {
        internal: 84,
        national: 84,
      },
      {
        internal: 85,
        national: 85,
      },
      {
        internal: 86,
        national: 86,
      },
      {
        internal: 87,
        national: 87,
      },
      {
        internal: 88,
        national: 88,
      },
      {
        internal: 89,
        national: 89,
      },
      {
        internal: 90,
        national: 90,
      },
      {
        internal: 91,
        national: 91,
      },
      {
        internal: 92,
        national: 92,
      },
      {
        internal: 93,
        national: 93,
      },
      {
        internal: 94,
        national: 94,
      },
      {
        internal: 95,
        national: 95,
      },
      {
        internal: 96,
        national: 96,
      },
      {
        internal: 97,
        national: 97,
      },
      {
        internal: 98,
        national: 98,
      },
      {
        internal: 99,
        national: 99,
      },
      {
        internal: 100,
        national: 100,
      },
      {
        internal: 101,
        national: 101,
      },
      {
        internal: 102,
        national: 102,
      },
      {
        internal: 103,
        national: 103,
      },
      {
        internal: 104,
        national: 104,
      },
      {
        internal: 105,
        national: 105,
      },
      {
        internal: 106,
        national: 106,
      },
      {
        internal: 107,
        national: 107,
      },
      {
        internal: 108,
        national: 108,
      },
      {
        internal: 109,
        national: 109,
      },
      {
        internal: 110,
        national: 110,
      },
      {
        internal: 111,
        national: 111,
      },
      {
        internal: 112,
        national: 112,
      },
      {
        internal: 113,
        national: 113,
      },
      {
        internal: 114,
        national: 114,
      },
      {
        internal: 115,
        national: 115,
      },
      {
        internal: 116,
        national: 116,
      },
      {
        internal: 117,
        national: 117,
      },
      {
        internal: 118,
        national: 118,
      },
      {
        internal: 119,
        national: 119,
      },
      {
        internal: 120,
        national: 120,
      },
      {
        internal: 121,
        national: 121,
      },
      {
        internal: 122,
        national: 122,
      },
      {
        internal: 123,
        national: 123,
      },
      {
        internal: 124,
        national: 124,
      },
      {
        internal: 125,
        national: 125,
      },
      {
        internal: 126,
        national: 126,
      },
      {
        internal: 127,
        national: 127,
      },
      {
        internal: 128,
        national: 128,
      },
      {
        internal: 129,
        national: 129,
      },
      {
        internal: 130,
        national: 130,
      },
      {
        internal: 131,
        national: 131,
      },
      {
        internal: 132,
        national: 132,
      },
      {
        internal: 133,
        national: 133,
      },
      {
        internal: 134,
        national: 134,
      },
      {
        internal: 135,
        national: 135,
      },
      {
        internal: 136,
        national: 136,
      },
      {
        internal: 137,
        national: 137,
      },
      {
        internal: 138,
        national: 138,
      },
      {
        internal: 139,
        national: 139,
      },
      {
        internal: 140,
        national: 140,
      },
      {
        internal: 141,
        national: 141,
      },
      {
        internal: 142,
        national: 142,
      },
      {
        internal: 143,
        national: 143,
      },
      {
        internal: 144,
        national: 144,
      },
      {
        internal: 145,
        national: 145,
      },
      {
        internal: 146,
        national: 146,
      },
      {
        internal: 147,
        national: 147,
      },
      {
        internal: 148,
        national: 148,
      },
      {
        internal: 149,
        national: 149,
      },
      {
        internal: 150,
        national: 150,
      },
      {
        internal: 151,
        national: 151,
      },
      {
        internal: 152,
        national: 152,
      },
      {
        internal: 153,
        national: 153,
      },
      {
        internal: 154,
        national: 154,
      },
      {
        internal: 155,
        national: 155,
      },
      {
        internal: 156,
        national: 156,
      },
      {
        internal: 157,
        national: 157,
      },
      {
        internal: 158,
        national: 158,
      },
      {
        internal: 159,
        national: 159,
      },
      {
        internal: 160,
        national: 160,
      },
      {
        internal: 161,
        national: 161,
      },
      {
        internal: 162,
        national: 162,
      },
      {
        internal: 163,
        national: 163,
      },
      {
        internal: 164,
        national: 164,
      },
      {
        internal: 165,
        national: 165,
      },
      {
        internal: 166,
        national: 166,
      },
      {
        internal: 167,
        national: 167,
      },
      {
        internal: 168,
        national: 168,
      },
      {
        internal: 169,
        national: 169,
      },
      {
        internal: 170,
        national: 170,
      },
      {
        internal: 171,
        national: 171,
      },
      {
        internal: 172,
        national: 172,
      },
      {
        internal: 173,
        national: 173,
      },
      {
        internal: 174,
        national: 174,
      },
      {
        internal: 175,
        national: 175,
      },
      {
        internal: 176,
        national: 176,
      },
      {
        internal: 177,
        national: 177,
      },
      {
        internal: 178,
        national: 178,
      },
      {
        internal: 179,
        national: 179,
      },
      {
        internal: 180,
        national: 180,
      },
      {
        internal: 181,
        national: 181,
      },
      {
        internal: 182,
        national: 182,
      },
      {
        internal: 183,
        national: 183,
      },
      {
        internal: 184,
        national: 184,
      },
      {
        internal: 185,
        national: 185,
      },
      {
        internal: 186,
        national: 186,
      },
      {
        internal: 187,
        national: 187,
      },
      {
        internal: 188,
        national: 188,
      },
      {
        internal: 189,
        national: 189,
      },
      {
        internal: 190,
        national: 190,
      },
      {
        internal: 191,
        national: 191,
      },
      {
        internal: 192,
        national: 192,
      },
      {
        internal: 193,
        national: 193,
      },
      {
        internal: 194,
        national: 194,
      },
      {
        internal: 195,
        national: 195,
      },
      {
        internal: 196,
        national: 196,
      },
      {
        internal: 197,
        national: 197,
      },
      {
        internal: 198,
        national: 198,
      },
      {
        internal: 199,
        national: 199,
      },
      {
        internal: 200,
        national: 200,
      },
      {
        internal: 201,
        national: 201,
      },
      {
        internal: 202,
        national: 202,
      },
      {
        internal: 203,
        national: 203,
      },
      {
        internal: 204,
        national: 204,
      },
      {
        internal: 205,
        national: 205,
      },
      {
        internal: 206,
        national: 206,
      },
      {
        internal: 207,
        national: 207,
      },
      {
        internal: 208,
        national: 208,
      },
      {
        internal: 209,
        national: 209,
      },
      {
        internal: 210,
        national: 210,
      },
      {
        internal: 211,
        national: 211,
      },
      {
        internal: 212,
        national: 212,
      },
      {
        internal: 213,
        national: 213,
      },
      {
        internal: 214,
        national: 214,
      },
      {
        internal: 215,
        national: 215,
      },
      {
        internal: 216,
        national: 216,
      },
      {
        internal: 217,
        national: 217,
      },
      {
        internal: 218,
        national: 218,
      },
      {
        internal: 219,
        national: 219,
      },
      {
        internal: 220,
        national: 220,
      },
      {
        internal: 221,
        national: 221,
      },
      {
        internal: 222,
        national: 222,
      },
      {
        internal: 223,
        national: 223,
      },
      {
        internal: 224,
        national: 224,
      },
      {
        internal: 225,
        national: 225,
      },
      {
        internal: 226,
        national: 226,
      },
      {
        internal: 227,
        national: 227,
      },
      {
        internal: 228,
        national: 228,
      },
      {
        internal: 229,
        national: 229,
      },
      {
        internal: 230,
        national: 230,
      },
      {
        internal: 231,
        national: 231,
      },
      {
        internal: 232,
        national: 232,
      },
      {
        internal: 233,
        national: 233,
      },
      {
        internal: 234,
        national: 234,
      },
      {
        internal: 235,
        national: 235,
      },
      {
        internal: 236,
        national: 236,
      },
      {
        internal: 237,
        national: 237,
      },
      {
        internal: 238,
        national: 238,
      },
      {
        internal: 239,
        national: 239,
      },
      {
        internal: 240,
        national: 240,
      },
      {
        internal: 241,
        national: 241,
      },
      {
        internal: 242,
        national: 242,
      },
      {
        internal: 243,
        national: 243,
      },
      {
        internal: 244,
        national: 244,
      },
      {
        internal: 245,
        national: 245,
      },
      {
        internal: 246,
        national: 246,
      },
      {
        internal: 247,
        national: 247,
      },
      {
        internal: 248,
        national: 248,
      },
      {
        internal: 249,
        national: 249,
      },
      {
        internal: 250,
        national: 250,
      },
      {
        internal: 251,
        national: 251,
      },
      {
        internal: 277,
        national: 252,
      },
      {
        internal: 278,
        national: 253,
      },
      {
        internal: 279,
        national: 254,
      },
      {
        internal: 280,
        national: 255,
      },
      {
        internal: 281,
        national: 256,
      },
      {
        internal: 282,
        national: 257,
      },
      {
        internal: 283,
        national: 258,
      },
      {
        internal: 284,
        national: 259,
      },
      {
        internal: 285,
        national: 260,
      },
      {
        internal: 286,
        national: 261,
      },
      {
        internal: 287,
        national: 262,
      },
      {
        internal: 288,
        national: 263,
      },
      {
        internal: 289,
        national: 264,
      },
      {
        internal: 290,
        national: 265,
      },
      {
        internal: 291,
        national: 266,
      },
      {
        internal: 292,
        national: 267,
      },
      {
        internal: 293,
        national: 268,
      },
      {
        internal: 294,
        national: 269,
      },
      {
        internal: 295,
        national: 270,
      },
      {
        internal: 296,
        national: 271,
      },
      {
        internal: 297,
        national: 272,
      },
      {
        internal: 298,
        national: 273,
      },
      {
        internal: 299,
        national: 274,
      },
      {
        internal: 300,
        national: 275,
      },
      {
        internal: 301,
        national: 290,
      },
      {
        internal: 302,
        national: 291,
      },
      {
        internal: 303,
        national: 292,
      },
      {
        internal: 304,
        national: 276,
      },
      {
        internal: 305,
        national: 277,
      },
      {
        internal: 306,
        national: 285,
      },
      {
        internal: 307,
        national: 286,
      },
      {
        internal: 308,
        national: 327,
      },
      {
        internal: 309,
        national: 278,
      },
      {
        internal: 310,
        national: 279,
      },
      {
        internal: 311,
        national: 283,
      },
      {
        internal: 312,
        national: 284,
      },
      {
        internal: 313,
        national: 320,
      },
      {
        internal: 314,
        national: 321,
      },
      {
        internal: 315,
        national: 300,
      },
      {
        internal: 316,
        national: 301,
      },
      {
        internal: 317,
        national: 352,
      },
      {
        internal: 318,
        national: 343,
      },
      {
        internal: 319,
        national: 344,
      },
      {
        internal: 320,
        national: 299,
      },
      {
        internal: 321,
        national: 324,
      },
      {
        internal: 322,
        national: 302,
      },
      {
        internal: 323,
        national: 339,
      },
      {
        internal: 324,
        national: 340,
      },
      {
        internal: 325,
        national: 370,
      },
      {
        internal: 326,
        national: 341,
      },
      {
        internal: 327,
        national: 342,
      },
      {
        internal: 328,
        national: 349,
      },
      {
        internal: 329,
        national: 350,
      },
      {
        internal: 330,
        national: 318,
      },
      {
        internal: 331,
        national: 319,
      },
      {
        internal: 332,
        national: 328,
      },
      {
        internal: 333,
        national: 329,
      },
      {
        internal: 334,
        national: 330,
      },
      {
        internal: 335,
        national: 296,
      },
      {
        internal: 336,
        national: 297,
      },
      {
        internal: 337,
        national: 309,
      },
      {
        internal: 338,
        national: 310,
      },
      {
        internal: 339,
        national: 322,
      },
      {
        internal: 340,
        national: 323,
      },
      {
        internal: 341,
        national: 363,
      },
      {
        internal: 342,
        national: 364,
      },
      {
        internal: 343,
        national: 365,
      },
      {
        internal: 344,
        national: 331,
      },
      {
        internal: 345,
        national: 332,
      },
      {
        internal: 346,
        national: 361,
      },
      {
        internal: 347,
        national: 362,
      },
      {
        internal: 348,
        national: 337,
      },
      {
        internal: 349,
        national: 338,
      },
      {
        internal: 350,
        national: 298,
      },
      {
        internal: 351,
        national: 325,
      },
      {
        internal: 352,
        national: 326,
      },
      {
        internal: 353,
        national: 311,
      },
      {
        internal: 354,
        national: 312,
      },
      {
        internal: 355,
        national: 303,
      },
      {
        internal: 356,
        national: 307,
      },
      {
        internal: 357,
        national: 308,
      },
      {
        internal: 358,
        national: 333,
      },
      {
        internal: 359,
        national: 334,
      },
      {
        internal: 360,
        national: 360,
      },
      {
        internal: 361,
        national: 355,
      },
      {
        internal: 362,
        national: 356,
      },
      {
        internal: 363,
        national: 315,
      },
      {
        internal: 364,
        national: 287,
      },
      {
        internal: 365,
        national: 288,
      },
      {
        internal: 366,
        national: 289,
      },
      {
        internal: 367,
        national: 316,
      },
      {
        internal: 368,
        national: 317,
      },
      {
        internal: 369,
        national: 357,
      },
      {
        internal: 370,
        national: 293,
      },
      {
        internal: 371,
        national: 294,
      },
      {
        internal: 372,
        national: 295,
      },
      {
        internal: 373,
        national: 366,
      },
      {
        internal: 374,
        national: 367,
      },
      {
        internal: 375,
        national: 368,
      },
      {
        internal: 376,
        national: 359,
      },
      {
        internal: 377,
        national: 353,
      },
      {
        internal: 378,
        national: 354,
      },
      {
        internal: 379,
        national: 336,
      },
      {
        internal: 380,
        national: 335,
      },
      {
        internal: 381,
        national: 369,
      },
      {
        internal: 382,
        national: 304,
      },
      {
        internal: 383,
        national: 305,
      },
      {
        internal: 384,
        national: 306,
      },
      {
        internal: 385,
        national: 351,
      },
      {
        internal: 386,
        national: 313,
      },
      {
        internal: 387,
        national: 314,
      },
      {
        internal: 388,
        national: 345,
      },
      {
        internal: 389,
        national: 346,
      },
      {
        internal: 390,
        national: 347,
      },
      {
        internal: 391,
        national: 348,
      },
      {
        internal: 392,
        national: 280,
      },
      {
        internal: 393,
        national: 281,
      },
      {
        internal: 394,
        national: 282,
      },
      {
        internal: 395,
        national: 371,
      },
      {
        internal: 396,
        national: 372,
      },
      {
        internal: 397,
        national: 373,
      },
      {
        internal: 398,
        national: 374,
      },
      {
        internal: 399,
        national: 375,
      },
      {
        internal: 400,
        national: 376,
      },
      {
        internal: 401,
        national: 377,
      },
      {
        internal: 402,
        national: 378,
      },
      {
        internal: 403,
        national: 379,
      },
      {
        internal: 404,
        national: 382,
      },
      {
        internal: 405,
        national: 383,
      },
      {
        internal: 406,
        national: 384,
      },
      {
        internal: 407,
        national: 380,
      },
      {
        internal: 408,
        national: 381,
      },
      {
        internal: 409,
        national: 385,
      },
      {
        internal: 410,
        national: 386,
      },
      {
        internal: 411,
        national: 358,
      },
    ],
  },
} satisfies Record<string, SpeciesIdMap>;

const GEN3_INTERNAL_TO_NATIONAL = new Map<number, number>(
  GEN3_SPECIES_ID_MAPS.emerald.entries.map((entry) => [entry.internal, entry.national])
);

export function getGen3NationalSpeciesId(internalSpecies: number): number {
  const map = GEN3_SPECIES_ID_MAPS.emerald;
  if (internalSpecies >= map.oldUnownInternalStart && internalSpecies <= map.oldUnownInternalEnd) {
    return map.oldUnownNational;
  }
  return GEN3_INTERNAL_TO_NATIONAL.get(internalSpecies) ?? internalSpecies;
}
